"""add key prefix to api_keys

Revision ID: f2a883e6a9ab
Revises: 39916e315df0
Create Date: 2026-03-13 13:24:24.104332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2a883e6a9ab"
down_revision: Union[str, None] = "39916e315df0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1 — add column as nullable first
    op.add_column("api_keys", sa.Column("key_prefix", sa.String(), nullable=True))

    # Step 2 — fill existing rows with a placeholder prefix
    op.execute(
        "UPDATE api_keys SET key_prefix = 'old_key_xxxx' WHERE key_prefix IS NULL"
    )

    # Step 3 — now make it NOT NULL
    op.alter_column("api_keys", "key_prefix", nullable=False)

    # Step 4 — add the index
    op.create_index("ix_api_keys_key_prefix", "api_keys", ["key_prefix"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_column("api_keys", "key_prefix")
    # ### end Alembic commands ###
